#!/bin/bash

# Usage: script/bootstrap-sc.sh
# Runs bootstrap for the self-contained docker profile, where
#   ruby itself is also part of the docker-compose stack

# This script gets run by the dockerfile itself to install dependencies, etc.
# It assumes we are on debian jessie, as that is the ruby:2.4.2 image base

set -e

# install ruby with rbenv if necessary (should not be if dockerfile is correctly updated)
dos2unix .ruby-version
rubyversion=$(cat .ruby-version)
rubyinstalled=$(ruby -v)

#debugging
#echo $rubyversion 
#echo $rubyinstalled
#$rubyinstalled == $rubyversion
#debugging

unset BUNDLER_VERSION

if [[ $rubyinstalled != *$rubyversion* ]]; then
  rbenv install $(cat .ruby-version)
  rbenv global $(cat .ruby-version)
fi

#install updated bundler
gem install bundler
bundle _2.0.2_ install

# install gems
bundle check 2>&1 || {
  echo "==> Installing gem dependencies..."
  bundle install --local --without production
  #bundle install 
}

#install yarn dependencies
# echo "==> Installing javascript dependencies..."
# yarnpkg install

# Install all of our JS dependencies if we need to
./bin/yarn check 2>&1 || {
 echo "==> Installing javascript dependencies..."
 ./bin/yarn install
}

# npm install uses package.json to install the dependencies mentioned in the json file
# RUN npm ci --only=production for production code.
echo "==> Installing node.js dependencies..."
npm install

