#!/bin/sh

# script/setup: Set up application for the first time after cloning, or set it
#               back to the initial first unused state.



set -e

cd "$(dirname "$0")/.."

unset BUNDLER_VERSION
if ! pgrep -x 'rinetd' > /dev/null
then
  rinetd
fi

echo "===> Preparing database..."
bin/rails db:setup

echo "===> Remove old logs and tempfiles..."
bin/rails log:clear tmp:clear

echo "===> Restart application server..."
bin/rails restart

if [ -z "$RAILS_ENV" ] && [ -z "$RACK_ENV" ]; then
  # Only things for a development environment will run inside here
  # Do things that need to be done to the application to set up for the first
  # time. Or things needed to be run to to reset the application back to first
  # use experience. These things are scoped to the application's domain.

  if ! [ -r ".env" ]; then
    cp .env-example .env
  fi
fi

echo "===> Waiting for the containers to mount..."
sleep 5

echo "==> Updating database..."
bin/rake db:migrate db:test:prepare

echo "===> Remove old logs and tempfiles..."
bin/rails log:clear tmp:clear

echo "===> Restart application server..."
bin/rails restart

test -z "$RACK_ENV" &&
  RACK_ENV='development'

# boot the app and any other necessary processes.
bundle exec foreman start -f Procfile.dev.sc

