apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-aks.yml convert
    kompose.version: 1.18.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: elasticsearch
  name: elasticsearch
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: elasticsearch
    spec:
      containers:
      - image: docker.elastic.co/elasticsearch/elasticsearch:6.3.2
        imagePullPolicy: IfNotPresent
        name: classroom-elasticsearch
        ports:
        - containerPort: 9300
        - containerPort: 9200
        resources: {}
        volumeMounts:
        - mountPath: /usr/share/elasticsearch/data
          name: classroom-classroom-data-elasticsearch-data
        - mountPath: /user/share/elasticsearch/logs
          name: classroom-classroom-data-elasticsearch-logs
      initContainers:
      - name: increase-the-vm-max-map-count
        image: busybox
        command:
        - sysctl
        - -w
        - vm.max_map_count=262144
        securityContext:
          privileged: true
      securityContext:
        fsGroup: 1000
      restartPolicy: Always
      volumes:
      - name: classroom-classroom-data-elasticsearch-data
        persistentVolumeClaim:
          claimName: classroom-classroom-data-elasticsearch-data
      - name: classroom-classroom-data-elasticsearch-logs
        persistentVolumeClaim:
          claimName: classroom-classroom-data-elasticsearch-logs
status: {}
